// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customTypes.proto

#include "customTypes.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace customTypes {

inline constexpr DecimalValue::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : units_{::int64_t{0}},
        nanos_{0},
        _cached_size_{0} {}

template <typename>
DecimalValue::DecimalValue(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct DecimalValueDefaultTypeInternal {
  DecimalValueDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DecimalValueDefaultTypeInternal() {}
  union {
    DecimalValue _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DecimalValueDefaultTypeInternal _DecimalValue_default_instance_;
}  // namespace customTypes
static ::_pb::Metadata file_level_metadata_customTypes_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_customTypes_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_customTypes_2eproto = nullptr;
const ::uint32_t TableStruct_customTypes_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::customTypes::DecimalValue, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::customTypes::DecimalValue, _impl_.units_),
    PROTOBUF_FIELD_OFFSET(::customTypes::DecimalValue, _impl_.nanos_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::customTypes::DecimalValue)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::customTypes::_DecimalValue_default_instance_._instance,
};
const char descriptor_table_protodef_customTypes_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\021customTypes.proto\022\013customTypes\",\n\014Deci"
    "malValue\022\r\n\005units\030\001 \001(\003\022\r\n\005nanos\030\002 \001(\017B\024"
    "\252\002\021Proto.CustomTypesb\006proto3"
};
static ::absl::once_flag descriptor_table_customTypes_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_customTypes_2eproto = {
    false,
    false,
    108,
    descriptor_table_protodef_customTypes_2eproto,
    "customTypes.proto",
    &descriptor_table_customTypes_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_customTypes_2eproto::offsets,
    file_level_metadata_customTypes_2eproto,
    file_level_enum_descriptors_customTypes_2eproto,
    file_level_service_descriptors_customTypes_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_customTypes_2eproto_getter() {
  return &descriptor_table_customTypes_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_customTypes_2eproto(&descriptor_table_customTypes_2eproto);
namespace customTypes {
// ===================================================================

class DecimalValue::_Internal {
 public:
};

DecimalValue::DecimalValue(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:customTypes.DecimalValue)
}
DecimalValue::DecimalValue(
    ::google::protobuf::Arena* arena, const DecimalValue& from)
    : DecimalValue(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE DecimalValue::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void DecimalValue::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, units_),
           0,
           offsetof(Impl_, nanos_) -
               offsetof(Impl_, units_) +
               sizeof(Impl_::nanos_));
}
DecimalValue::~DecimalValue() {
  // @@protoc_insertion_point(destructor:customTypes.DecimalValue)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DecimalValue::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

//PROTOBUF_NOINLINE void DecimalValue::Clear() {
//// @@protoc_insertion_point(message_clear_start:customTypes.DecimalValue)
//  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
//  ::uint32_t cached_has_bits = 0;
//  // Prevent compiler warnings about cached_has_bits being unused
//  (void) cached_has_bits;
//
//  ::memset(&_impl_.units_, 0, static_cast<::size_t>(
//      reinterpret_cast<char*>(&_impl_.nanos_) -
//      reinterpret_cast<char*>(&_impl_.units_)) + sizeof(_impl_.nanos_));
//  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
//}

const char* DecimalValue::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> DecimalValue::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_DecimalValue_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // sfixed32 nanos = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(DecimalValue, _impl_.nanos_)}},
    // int64 units = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(DecimalValue, _impl_.units_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(DecimalValue, _impl_.units_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 units = 1;
    {PROTOBUF_FIELD_OFFSET(DecimalValue, _impl_.units_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // sfixed32 nanos = 2;
    {PROTOBUF_FIELD_OFFSET(DecimalValue, _impl_.nanos_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kSFixed32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* DecimalValue::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:customTypes.DecimalValue)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 units = 1;
  if (this->_internal_units() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_units(), target);
  }

  // sfixed32 nanos = 2;
  if (this->_internal_nanos() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSFixed32ToArray(
        2, this->_internal_nanos(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:customTypes.DecimalValue)
  return target;
}

::size_t DecimalValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:customTypes.DecimalValue)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 units = 1;
  if (this->_internal_units() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_units());
  }

  // sfixed32 nanos = 2;
  if (this->_internal_nanos() != 0) {
    total_size += 5;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData DecimalValue::_class_data_ = {
    DecimalValue::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* DecimalValue::GetClassData() const {
  return &_class_data_;
}

void DecimalValue::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<DecimalValue*>(&to_msg);
  auto& from = static_cast<const DecimalValue&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:customTypes.DecimalValue)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_units() != 0) {
    _this->_internal_set_units(from._internal_units());
  }
  if (from._internal_nanos() != 0) {
    _this->_internal_set_nanos(from._internal_nanos());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DecimalValue::CopyFrom(const DecimalValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:customTypes.DecimalValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool DecimalValue::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* DecimalValue::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void DecimalValue::InternalSwap(DecimalValue* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  //::google::protobuf::internal::memswap<
/*      PROTOBUF_FIELD_OFFSET(DecimalValue, _impl_.nanos_)
      + sizeof(DecimalValue::_impl_.nanos_)
      - PROTOBUF_FIELD_OFFSET(DecimalValue, _impl_.units_)>*/(
          reinterpret_cast<char*>(&_impl_.units_),
          reinterpret_cast<char*>(&other->_impl_.units_));
}

::google::protobuf::Metadata DecimalValue::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_customTypes_2eproto_getter, &descriptor_table_customTypes_2eproto_once,
      file_level_metadata_customTypes_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace customTypes
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
