// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customTypes.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_customTypes_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_customTypes_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_customTypes_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_customTypes_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_customTypes_2eproto;
namespace customTypes {
class DecimalValue;
struct DecimalValueDefaultTypeInternal;
extern DecimalValueDefaultTypeInternal _DecimalValue_default_instance_;
}  // namespace customTypes
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace customTypes {

// ===================================================================


// -------------------------------------------------------------------

class DecimalValue final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:customTypes.DecimalValue) */ {
 public:
  inline DecimalValue() : DecimalValue(nullptr) {}
  ~DecimalValue() override;
  template<typename = void>
  explicit DecimalValue(::google::protobuf::internal::ConstantInitialized);

  inline DecimalValue(const DecimalValue& from)
      : DecimalValue(nullptr, from) {}
  DecimalValue(DecimalValue&& from) noexcept
    : DecimalValue() {
    *this = ::std::move(from);
  }

  inline DecimalValue& operator=(const DecimalValue& from) {
    CopyFrom(from);
    return *this;
  }
  inline DecimalValue& operator=(DecimalValue&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DecimalValue& default_instance() {
    return *internal_default_instance();
  }
  static inline const DecimalValue* internal_default_instance() {
    return reinterpret_cast<const DecimalValue*>(
               &_DecimalValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DecimalValue& a, DecimalValue& b) {
    a.Swap(&b);
  }
  inline void Swap(DecimalValue* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DecimalValue* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DecimalValue* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DecimalValue>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DecimalValue& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const DecimalValue& from) {
    DecimalValue::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  //PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(DecimalValue* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "customTypes.DecimalValue";
  }
  protected:
  explicit DecimalValue(::google::protobuf::Arena* arena);
  DecimalValue(::google::protobuf::Arena* arena, const DecimalValue& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUnitsFieldNumber = 1,
    kNanosFieldNumber = 2,
  };
  // int64 units = 1;
  void clear_units() ;
  ::int64_t units() const;
  void set_units(::int64_t value);

  private:
  ::int64_t _internal_units() const;
  void _internal_set_units(::int64_t value);

  public:
  // sfixed32 nanos = 2;
  void clear_nanos() ;
  ::int32_t nanos() const;
  void set_nanos(::int32_t value);

  private:
  ::int32_t _internal_nanos() const;
  void _internal_set_nanos(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:customTypes.DecimalValue)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::int64_t units_;
    ::int32_t nanos_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    //PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_customTypes_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// DecimalValue

// int64 units = 1;
inline void DecimalValue::clear_units() {
  //PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.units_ = ::int64_t{0};
}
inline ::int64_t DecimalValue::units() const {
  // @@protoc_insertion_point(field_get:customTypes.DecimalValue.units)
  return _internal_units();
}
inline void DecimalValue::set_units(::int64_t value) {
  _internal_set_units(value);
  // @@protoc_insertion_point(field_set:customTypes.DecimalValue.units)
}
inline ::int64_t DecimalValue::_internal_units() const {
  //PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.units_;
}
inline void DecimalValue::_internal_set_units(::int64_t value) {
  //PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.units_ = value;
}

// sfixed32 nanos = 2;
inline void DecimalValue::clear_nanos() {
  //PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.nanos_ = 0;
}
inline ::int32_t DecimalValue::nanos() const {
  // @@protoc_insertion_point(field_get:customTypes.DecimalValue.nanos)
  return _internal_nanos();
}
inline void DecimalValue::set_nanos(::int32_t value) {
  _internal_set_nanos(value);
  // @@protoc_insertion_point(field_set:customTypes.DecimalValue.nanos)
}
inline ::int32_t DecimalValue::_internal_nanos() const {
  //PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.nanos_;
}
inline void DecimalValue::_internal_set_nanos(::int32_t value) {
  //PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.nanos_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace customTypes


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_customTypes_2eproto_2epb_2eh
